{{- $db := .Values.database | default dict -}}
{{- $dbHost := (hasKey $db "host") | ternary $db.host (printf "%s-db" (include "backend.fullname" .)) -}}
{{- $dbPort := (hasKey $db "port") | ternary $db.port "5432" -}}
{{- $dbName := (hasKey $db "name") | ternary $db.name "appdb" -}}
{{- $dbUser := (hasKey $db "username") | ternary $db.username "appuser" -}}
{{- $dbPass := (hasKey $db "password") | ternary $db.password "secretpassword" -}}
{{- $connStr := (hasKey $db "connectionString") | ternary $db.connectionString (printf "postgres://%s:%s@%s:%s/%s" $dbUser $dbPass $dbHost $dbPort $dbName) -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: {{ .Values.labels.app }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: DATABASE_URL
              value: {{ $connStr | quote }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}-db
spec:
  selector:
    app: {{ include "backend.fullname" . }}-db
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "backend.fullname" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "backend.fullname" . }}-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: {{ $dbName }}
            - name: POSTGRES_USER
              value: {{ $dbUser }}
            - name: POSTGRES_PASSWORD
              value: {{ $dbPass }}
          ports:
            - containerPort: 5432
